blank_issues_enabled: false
contact_links:
  - name: ğŸ¬ Animation Request
    url: https://github.com/NerdBoi008/clipmotion/issues/new?template=animation-request.md
    about: Use this template to request new animations or features.
  - name: ğŸ Bug Report
    url: https://github.com/NerdBoi008/clipmotion/issues/new?template=bug-report.md
    about: Use this template to report bugs or unexpected behavior.
